# Generated by Django 4.1.7 on 2024-03-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_term_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
