# Generated by Django 4.1.7 on 2024-03-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_role_roletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='roletype',
            field=models.CharField(choices=[('EX', 'Executive'), ('CO', 'Councillor'), ('RE', 'Representative'), ('DI', 'Director'), ('OT', 'Other'), ('OF', 'Officer')], max_length=2, null=True),
        ),
    ]
